<a href="https://colab.research.google.com/github/GTD2101-ACD-GA-AD22/pandas-ricardo-qm/blob/main/05.%20DataMissing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tipos de Datos y Valores Extraviados

En este JNB se revisar√° el tema de Tipos de Datos y Valores Extraviados en Pandas.

In [1]:
import pandas as pd
reviews = pd.read_csv("https://raw.githubusercontent.com/GTD2101-ACD-GA-AD22/pandas-ricardo-qm/main/data/winemag-data-130k-v2.csv", index_col=0)
pd.set_option('max_rows', 5)

In [2]:
reviews.price.dtype

dtype('float64')

In [3]:
reviews.dtypes

country        object
description    object
                ...
variety        object
winery         object
Length: 13, dtype: object

In [4]:
reviews.points.astype('float64')

0         87.0
1         87.0
          ...
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

In [5]:
reviews.index.dtype

dtype('int64')

# Datos extraviados

En Pandas es importante tener la posibilidad de manejar situaciones en las que nos hagan falta datos y tomar decisiones respecto a esto.

In [6]:
reviews.isnull()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,False,False,False,False,True,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,False,False,True,False,False,False,False,True,False,False,False,False,False
129970,False,False,False,False,False,False,False,True,False,False,False,False,False

In [7]:
reviews.points.isnull()

0         False
1         False
          ...
129969    False
129970    False
Name: points, Length: 129971, dtype: bool

In [8]:
reviews[pd.isnull(reviews.country)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,B√ºy√ºl√ºbaƒü 2012 Shah Red,Red Blend,B√ºy√ºl√ºbaƒü
129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [11]:
reviews.region_2.fillna("Unknown")

0         Unknown
1         Unknown
           ...
129969    Unknown
129970    Unknown
Name: region_2, Length: 129971, dtype: object

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulk√† Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O‚ÄôKeefe,@kerinokeefe,Nicosia 2013 Vulk√† Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuv√©e Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuv√©e Car...,Gew√ºrztraminer,Domaine Schoffit

In [13]:
reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

0            @kerino
1         @vossroger
             ...
129969    @vossroger
129970    @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object